[profile.default]
src = 'contracts'
out = 'out'
test = 'test/foundry'
libs = ['node_modules', 'lib']
script = 'scripts/foundry'
cache_path = 'cache-forge'
gas_reports = ["*"]
optimizer_runs=1000000
# For vaultManagerListing
# optimizer_runs=100


solc_version = '0.8.17'

ffi = true

[fuzz]
runs = 500

[invariant]
runs = 500

[rpc_endpoints]
arbitrum = "${ETH_NODE_URI_ARBITRUM}"
mainnet = "${ETH_NODE_URI_MAINNET}"
optimism = "${ETH_NODE_URI_OPTIMISM}"
polygon = "${ETH_NODE_URI_POLYGON}"
goerli = "${ETH_NODE_URI_GOERLI}"
fork = "${ETH_NODE_URI_FORK}"

[etherscan]
arbitrum = { key = "${ARBITRUM_ETHERSCAN_API_KEY}" }
mainnet = { key = "${MAINNET_ETHERSCAN_API_KEY}" }
optimism = { key = "${OPTIMISM_ETHERSCAN_API_KEY}" }
polygon = { key = "${POLYGON_ETHERSCAN_API_KEY}" }
goerli = { key = "${GOERLI_ETHERSCAN_API_KEY}" }
